### PR TITLE
#172713792 Week III feedback

### PR DESCRIPTION
**Pull request by EugeneMunya**
#### What does this PR do?
- make this application mobile-friendly
#### Description of Task to be completed?
- make sign-in form responsive
- make sign up page responsive
- make landing page responsive
#### How should this be manually tested?
opening your terminal and run this command `git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.git`
- run `cd knights-bn-frontend folder`
- run `git fetch && git checkout ft-week-3-feedback-172713792`
- run npm install and then run npm run dev-start
- test all pages against the mobile view
#### landing page
Screen Shot 2020-05-18 at 09 34 39

#### sign up page
Screen Shot 2020-05-19 at 08 43 28

#### Login page
Screen Shot 2020-05-19 at 08 42 58

### CODE REVIEW

**Comment by Kagorora** [comment]
@EugeneMunya Good work so far, Here are my feedback

1. You have changed the look of the login and SIgnup, Any particular reason.

2. Some lines are not covered

3. There is no response when a user tries to sign with a nonr egistered email.

**Comment by EugeneMunya** [comment]
> @EugeneMunya Good work so far, Here are my feedback
> 
> 1. You have changed the look of the login and SIgnup, Any particular reason.
> 2. Some lines are not covered
> 3. There is no response when a user tries to sign with a nonregistered email.
 I had to change them to make them work in both mobile and big devices, the buttons and forms used when designing them before were not easy to make them working in mobile, I don't even get you well what do you mean by I changed the look.
Can you provide a screenshot of the lines that are not covered?

**Comment by EugeneMunya** [comment]
> > @EugeneMunya Good work so far, Here are my feedback
> > 
> > 1. You have changed the look of the login and SIgnup, Any particular reason.
> > 2. Some lines are not covered
> > 3. There is no response when a user tries to sign with a nonregistered email.
> >    I had to change them to make them work in both mobile and big devices, the buttons and forms used when designing them before were not easy to make them working in mobile, I don't even get you well what do you mean by I changed the look.
> >    Can you provide a screenshot of the lines that are not covered?

On my end messages displaying well check again

**Comment by Kagorora** [comment]
@eugen, Good work so far,

Here are further feedback,

1. Try to have a UI similar to the mockup(Login && signup) for us to have consistency UI pages should look alike.

2. This error message is grammatically incorrect.

 You could write: "That email is taken, Try another"

Screen Shot 2020-05-18 at 13 07 34

**Comment by EugeneMunya** [comment]
> @eugen, Good work so far,
> 
> Here are further feedback,
> 
> 1. Try to have a UI similar to the mockup(Login && signup) for us to have consistency UI pages should look alike.
> 2. This error message is grammatically incorrect.
> 
> You could write: "That email is taken, Try another"
> 
> Screen Shot 2020-05-18 at 13 07 34

That validation message is coming from the server I will correct it when I will be resolving the issues I have found

**Comment by Kagorora** [comment]
@EugeneMunya , The login && signup page height is very long if you could reduce it

**Review by Kagorora — APPROVED** [review]

**Comment by Niyonsengaeric** [comment]
@EugeneMunya  
make the footer fixed at the bottom on every page, also add padding-bottom on the sign-up form

**Review by Niyonsengaeric — CHANGES_REQUESTED** [review]
@EugeneMunya  
make the footer fixed at the bottom and centered on every page, also add padding-bottom on the sign-up form

**Review by Niyonsengaeric — APPROVED** [review]

**Pull request closed without merging**
