### PR TITLE
#170947603 Create signup page

### PR DESCRIPTION
**Pull request by T2Wil**
#### What does this PR do?
- Adds signup page.
#### Description of Task to be completed?
- Design UI
- connect to the API
#### How should this be manually tested?
- run `git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.git` to have the repo locally.
- run `cd /knights-bn-frontend.git` to get inside the project directory.
- run `git checkout -t origin/ft-signup-170947603` to switch to this branch.
- run `npm i` to install all dependencies.
- run `npm dev-start` to start the server.
- the browser should start by itself to the homePage.
- type in `http://localhost:8080/signup` to get the signup page
- populate in the required fields and hit `SIGN UP`
- after clicking on the `account verification link` via your email make sure to change the redirecting URL in the URL path to match the local branch: 
```
ex: http://localhost:8080/
```

#### What are the relevant pivotal tracker stories?
[link](https://www.pivotaltracker.com/story/show/170947603)

#### Screenshots (if appropriate)
image

image

image

### The email verification link is sent after correct data validation.
image

### CODE REVIEW

**Comment by Niyonsengaeric** [comment]
Screen Shot 2020-05-05 at 17 40 45
@T2Wil  it is hanging on this page

**Comment by T2Wil** [comment]
> Screen Shot 2020-05-05 at 17 40 45
> 
> @T2Wil it is hanging on this page

Thanks @Niyonsengaeric , There was an error in calling thunk but now is fixed!

**Comment by Niyonsengaeric** [comment]
1. change your screenshots
2. change social login text to `Sign up with Google` and `Sign up with Facebook`
3. squash commits 
4. your coveralls is failing

**Review by Kagorora — COMMENTED** [review]
@T2Wil , Good work so far, A quick feedback , when I Signup using an already existing email, I was told the email exists but in the web url and that might be confusing to the client, here is what the page looks like.

Screen Shot 2020-05-06 at 09 58 10

**Comment by T2Wil** [comment]
> @T2Wil , Good work so far, A quick feedback , when I Signup using an already existing email, I was told the email exists but in the web url and that might be confusing to the client, here is what the page looks like.
> 
> Screen Shot 2020-05-06 at 09 58 10

Yeah @Kagorora , it is confusing. 
But as the branch is not yet deployed the quick solution is to change the app `URL path` to match the local environment.
replace `https://knights-bn-frontend.herokuapp.com` with `localhost:8080` make sure the port matches your server's port.

**Review by Kagorora — APPROVED** [review]

**Review by EugeneMunya — APPROVED** [review]

**Review by Niyonsengaeric — APPROVED** [review]

**Review by kagabof — APPROVED** [review]
Well done.

**Pull request merged**
