### PR TITLE
#172650962: Design landing page

### PR DESCRIPTION
**Pull request by Kagorora**
#### What does this PR do?

- This PR will design the Landing Page

#### Description of Task to be completed?

- Add an Image on the landing page

- Add Project description

- Add Get Started button that direct to Login

#### How should this be manually tested?

- clone the project :

       git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.gi`

- go to this branch by running :  

       git checkout ft-design-landingPage-172650962

- Install dependencies: 

       npm run i

- Run the project

        npm run dev-start

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [172650962](https://www.pivotaltracker.com/story/show/172650962)

#### Screenshots (if appropriate)

Screen Shot 2020-05-06 at 13 55 04

#### Questions:

- N/A

### CODE REVIEW

**Review by T2Wil — APPROVED** [review]
nice looking page @Kagorora

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-06 at 15 08 21
Try to make it mobile friendly

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-06 at 15 09 56
Use the images that explain the idea behind this project

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-06 at 15 09 56
Add links that users will use to choose languages

**Review by kagabof — CHANGES_REQUESTED** [review]
Please rebase.

**Review by EugeneMunya — APPROVED** [review]

**Review by kagabof — APPROVED** [review]
well done.

**Pull request merged**
