### PR TITLE
#170947606 Login via Facebook and Google.

### PR DESCRIPTION
**Pull request by Niyonsengaeric**
#### What does this PR do?
- Login via Facebook and Google.
#### Description of Task to be completed?
- Add the Google and Facebook login functionality.
- Test the components
#### How should this be manually tested?
- run `git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.git` to clone the repo.
- run `cd knights-bn-backend` in your terminal to enter into the repository.
- run `git fetch ` command to download commits, files, and refs from a remote repository into your local repo.
- run `git checkout ft-social-login-170947606` to switch to this branch.
- run `npm install` to install dependencies.
- run `npm run dev-start` to start the application.
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?

[#170947606](https://www.pivotaltracker.com/story/show/170947606)

#### Screenshots (if appropriate)

Screen Shot 2020-05-04 at 10 24 20

#### Questions:
N/A

### CODE REVIEW

**Comment by T2Wil** [comment]
I am getting unreachable page after trying to log in on both social logins :

image

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-04 at 13 14 39
Make it mobile-friendly

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-04 at 13 17 15
Try to avoid this cause when it starts to load it shows me that error

**Comment by EugeneMunya** [comment]
increase test coverage at least up to 95%
Screen Shot 2020-05-04 at 13 20 35

**Comment by Niyonsengaeric** [comment]
> I am getting unreachable page after trying to log in on both social logins :
> 
> image

@T2Wil  you forget to start the application `npm run dev-start`

**Comment by Niyonsengaeric** [comment]
> increase test coverage at least up to 95%
> Screen Shot 2020-05-04 at 13 20 35

@EugeneMunya  Login page has many options including login using a social account and login using app user email and password so here I test the one for login using social account and it is full test other test is done through this [PR](https://github.com/Stackup-Rwanda/knights-bn-frontend/pull/10)

**Comment by Niyonsengaeric** [comment]
> Screen Shot 2020-05-04 at 13 14 39
> 
> Make it mobile-friendly

@EugeneMunya let me work on it

**Comment by EugeneMunya** [comment]
make an entire button a link no portion of it
Screen Shot 2020-05-04 at 13 29 49

**Comment by Kagorora** [comment]
@Niyonsengaeric , Quick feedback

1. The Facebook logo color is **blue-sky** not that one you used (It may confuse someone).
         Facebook logo looks like this
         
Screen Shot 2020-05-04 at 16 16 47


2. Using Facebook, I 'm having this error

Screen Shot 2020-05-04 at 16 11 43

3. **This is a question**, Does users allowed to login without having to create accounts,
as I can see I am allowed to login.

4. **For a better design**, could you design those buttons(Social Login Button) so that they look like a button.

Screen Shot 2020-05-04 at 16 13 26

**Comment by Niyonsengaeric** [comment]
> > I am getting unreachable page after trying to log in on both social logins :
> > image
> 
> @T2Wil you forget to start the application `npm run dev-start`
remember also to run `npm install ` as mentioned in PR description

**Comment by Niyonsengaeric** [comment]
> make an entire button a link no portion of it
> Screen Shot 2020-05-04 at 13 29 49

done!

**Comment by Niyonsengaeric** [comment]
> @Niyonsengaeric , Quick feedback
> 
> 1. The Facebook logo color is **blue-sky** not that one you used (It may confuse someone).
>    Facebook logo looks like this
> 
> Screen Shot 2020-05-04 at 16 16 47
> 
> 1. Using Facebook, I 'm having this error
> 
> Screen Shot 2020-05-04 at 16 11 43
> 
> 1. **This is a question**, Does users allowed to login without having to create accounts,
>    as I can see I am allowed to login.
> 2. **For a better design**, could you design those buttons(Social Login Button) so that they look like a button.
> 
> Screen Shot 2020-05-04 at 16 13 26

@Kagorora  on question number 3, The answer is yes what you need to have is your google or Facebook account and our system will bundle the rest.
on question number 2 the reason why it is failing it is that our application is in development mode so all you need to do is ask @T2Wil  to add your email in-app tester email so that you can test the APP.
- all thor feedbacks have been implemented you can take a look.

**Review by T2Wil — APPROVED** [review]

**Review by Kagorora — APPROVED** [review]

**Review by EugeneMunya — CHANGES_REQUESTED** [review]
You have too much commits  reduce them it would affect us in the future

**Comment by EugeneMunya** [comment]
Screen Shot 2020-05-05 at 12 35 24
Reduce these too much commits they might affect us in the future

**Pull request closed without merging**
