### PR TITLE
170947604-ft(reset):reset password form

### PR DESCRIPTION
**Pull request by EugeneMunya**
#### What does this PR do?
- presenting a user the first form to reset password
#### Description of Task to be completed?
- a form that allows user to enter his/her email in order to reset password
#### How should this be manually tested?
- opening your terminal and run this command `git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.git` 
- run `cd knights-bn-frontend folder`
 - run `git fetch && git checkout ft-reset-password-170947604` 
- run `npm install` and then run `npm run dev-start`
-  paste this URL `http://localhost:8080/forgetpassword` in your browser, 
- after you successfully request to reset the password you will receive an email that contains a link you will use to write new credentials, then click on that link and it will take you to the new browser tab. since we are testing locally change the URL where there is `https://knights-bn-frontend.herokuapp.com` replace it with `http://localhost:8080` and type your new credentials and send.
#### What are the relevant pivotal tracker stories?
[#170947604](https://www.pivotaltracker.com/story/show/170947604)
#### Screenshots (if appropriate)
Screen Shot 2020-05-04 at 12 45 17

Screen Shot 2020-05-04 at 12 45 55

### CODE REVIEW

**Comment by Niyonsengaeric** [comment]
Screen Shot 2020-05-04 at 14 28 32
@EugeneMunya  can you change the way your message is showing

**Comment by T2Wil** [comment]
nice work @EugeneMunya , 
I am receiving the email as expected but the link to verify the account is not working (I can't reset my password)


image

**Comment by T2Wil** [comment]
@EugeneMunya , You might consider giving a green colour on success messages or alerts

image

**Comment by T2Wil** [comment]
Could you make these 2 errors the same? (As they all validate password)

Error 1: 
image


Error 2:
image

**Comment by EugeneMunya** [comment]
> @EugeneMunya , You might consider giving a green colour on success messages or alerts
> 
> image

I have implemented your feedback check again

**Comment by EugeneMunya** [comment]
> Could you make these 2 errors the same? (As they all validate password)
> 
> Error 1:
> image
> 
> Error 2:
> image

I resolved it check again

**Comment by EugeneMunya** [comment]
> Screen Shot 2020-05-04 at 14 28 32
> 
> @EugeneMunya can you change the way your message is showing

Now messages are displaying very nice check again

**Pull request closed without merging**
